In [1]:
import numpy as np

In [7]:
x=np.array([1,2,3,4,5])
print(x) #1d 
print(x.ndim)
print(type(x))

[1 2 3 4 5]
1
<class 'numpy.ndarray'>


In [9]:
x=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(x) #2d 
print(x.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]]
2


In [3]:
x=np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(x) #3d 
print(x.ndim) 

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]
3


In [4]:
x=np.random.randint(10,size=6)
x

array([1, 9, 4, 8, 6, 5])

In [2]:
x=np.random.randint(20,size=(5,6))
x

array([[ 2, 16,  4, 10, 15,  3],
       [ 2,  3, 16, 11, 13,  5],
       [ 6, 11, 18,  4,  7,  7],
       [ 7,  1,  6, 12,  6, 12],
       [ 2, 13,  1, 19, 11,  5]])

In [3]:
x=np.random.randint(20,size=(3,2,4))
x

array([[[ 7, 12,  8, 13],
        [14,  0, 10, 18]],

       [[17, 14,  5,  1],
        [12,  8, 11,  7]],

       [[18,  4, 16, 13],
        [14,  4, 17,  3]]])

In [6]:
x=20
np.floor_divide(x,5)

4

In [10]:
x=np.arange(4,10,2)
x

array([4, 6, 8])

## taking array from user

In [8]:
l=[]

for i in range(1,5):
    value=int(input("values : ")) #input always takes values as a string , thats why i used int(input)
    l.append(value)
    
print(l)
print(type(l))
print(np.array(l))
a=np.array(l)
print(type(a))

values : 10
values : 12
values : 14
values : 16
[10, 12, 14, 16]
<class 'list'>
[10 12 14 16]
<class 'numpy.ndarray'>


## 10D array

In [10]:
x=np.array([1,2,3,4],ndmin=10)
print(x)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


## Zeroes

In [13]:
#1d

x=np.zeros(4)
x

array([0., 0., 0., 0.])

In [16]:
#2d

x=np.zeros((2,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#3d

x=np.zeros(((3,5,4)))
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Ones

In [19]:
#1d

x=np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [20]:
#2d

x=np.ones((2,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
#3d

x=np.ones(((3,3,4)))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# Empty

In [23]:
x=np.empty(6)
x #copy the previous memory's data

array([1., 1., 1., 1., 1., 1.])

## Range

In [26]:
y= np.arange(4) #first 4 values of counting no.'s
y 
                #? only work for 1d.

array([0, 1, 2, 3])

In [35]:
x1=np.arange(10,30,2) #syntax (start:end:step) end values doesn't print
x1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [54]:
x1=np.arange(10,30,2.5) #syntax (start:end:step) end values doesn't print
x1

array([10. , 12.5, 15. , 17.5, 20. , 22.5, 25. , 27.5])

## Diagonal

In [32]:
k= np.eye(6)
k #add 1 in diagonals of array

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Linspace

In [40]:
x2= np.linspace(1,10,num=6)   #fetches 6 numbers between 1 to 10 with equal distances
x2
#starting and end value both get printed.

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

## Create numpy arrays with random numbers

## Rand()

In [42]:
#create random value between 0 to 1

x=np.random.rand(5)
x

array([0.2429922 , 0.94188011, 0.23161526, 0.17438474, 0.17884233])

In [45]:
x=np.random.rand(2,4)
x

array([[0.68822794, 0.76262473, 0.51899645, 0.91168391],
       [0.72631045, 0.7678811 , 0.43448564, 0.16251665]])

In [48]:
x=np.random.rand(2,4,5)
x

array([[[0.50456502, 0.66862973, 0.01777946, 0.93647989, 0.24525906],
        [0.89196146, 0.04861665, 0.88976819, 0.04868435, 0.6231631 ],
        [0.43239995, 0.93990271, 0.02225559, 0.03213558, 0.23446463],
        [0.36412367, 0.53054742, 0.04365767, 0.0711958 , 0.87040265]],

       [[0.8318722 , 0.65620912, 0.61663216, 0.76609843, 0.15385836],
        [0.99472145, 0.32454442, 0.51583915, 0.92842212, 0.38433892],
        [0.88566633, 0.98897717, 0.26901722, 0.90733885, 0.58842529],
        [0.64496758, 0.91154297, 0.10743067, 0.86422617, 0.51576354]]])

In [49]:
x=np.random.rand(2,2,2,2)
x

array([[[[0.61025822, 0.25789203],
         [0.06350268, 0.9160463 ]],

        [[0.9292832 , 0.52754896],
         [0.38079557, 0.73567528]]],


       [[[0.73719141, 0.82176155],
         [0.24485741, 0.67917618]],

        [[0.50919936, 0.5049976 ],
         [0.15862613, 0.34043294]]]])

## Randn()

In [51]:
#values close to 0 means negative to 0.

x=np.random.randn(5)
x

array([ 0.73398747, -0.68027293, -0.62658796, -0.39198469, -2.00767285])

In [55]:
x=np.random.randn(2,4)
x

array([[-0.62946243,  0.71496698, -0.84621668, -1.34778689],
       [-0.20994775, -0.43318213,  0.80031968,  0.51352864]])

## Ranf()

In [57]:
#random floats in the half open interval[0.0,1.0] 1 is not included

x=np.random.ranf(5)
x

array([0.6577031 , 0.13748556, 0.62326489, 0.3326247 , 0.03639338])

## Randint()

In [60]:
#pass min or max values and it generate random numbers between them.

#syntax : np.random.randint(min,max,total numbers)

x=np.random.randint(10,40,30)
x #numbers can be repeated , but min or max values doesn't print

array([20, 31, 25, 26, 35, 24, 27, 26, 25, 37, 23, 14, 27, 25, 25, 18, 14,
       15, 28, 35, 37, 25, 21, 38, 17, 24, 24, 11, 29, 16])

## Shape()

In [61]:
x=np.array([[1,2,3,4],[1,2,3,4]])
x.shape

(2, 4)

In [64]:
x=np.array([1,2,3,4],ndmin=4)
print(x)
print(x.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [4]:
np.nan

nan

In [6]:
np.nan==np.nan ?

False

## array

In [4]:
for i in np.nditer(x):
    print(i)

1
2
3
4
5
1
2
3
4
5
1
2
3
4
5


In [5]:
n1=np.matrix([[1,2,3],[4,5,6]])
n1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [9]:
n2=np.matrix([[7,8,9],[11,12,13]])
n2

matrix([[ 7,  8,  9],
        [11, 12, 13]])

In [11]:
z=n1.n2

AttributeError: 'matrix' object has no attribute 'n2'