# installing python:

conda install numpy

pip install numpy

# for importing:
import numpy as np

In [1]:
#We'll cover a few categories of basic array manipulations here:
#Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
#Indexing of arrays: Getting and setting the value of individual array elements
#Slicing of arrays: Getting and setting smaller subarrays within a larger array
#Reshaping of arrays: Changing the shape of a given array
#Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

# Creating Numpy Array

In [1]:
import numpy as np

In [4]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print(x1)
print()
print(x2)
print()
print(x3)

[8 5 9 1 1 5]

[[2 6 2 0]
 [2 0 7 3]
 [3 8 2 8]]

[[[4 0 0 2 8]
  [4 8 7 0 7]
  [2 4 1 1 9]
  [7 5 8 8 0]]

 [[7 8 5 7 0]
  [7 0 7 5 1]
  [8 1 9 2 9]
  [8 3 0 3 5]]

 [[2 2 3 7 4]
  [1 9 0 3 9]
  [2 3 0 5 4]
  [1 4 5 7 7]]]


In [22]:
x3[0:2,0:2,1:2]

8

In [18]:
x3

array([[[5, 3, 3, 6, 4],
        [8, 2, 3, 0, 4],
        [5, 1, 3, 6, 2],
        [0, 7, 7, 9, 4]],

       [[7, 9, 7, 7, 0],
        [5, 8, 4, 2, 4],
        [2, 5, 0, 7, 9],
        [1, 8, 9, 1, 4]],

       [[8, 8, 5, 4, 1],
        [9, 9, 3, 0, 1],
        [8, 5, 7, 2, 5],
        [6, 4, 9, 3, 9]]])

In [3]:
x1

array([1, 6, 8, 4, 1, 9])

In [82]:
x2

array([[8, 0, 8, 3],
       [6, 0, 2, 4],
       [6, 2, 0, 8]])

In [83]:
x3

array([[[8, 8, 1, 5, 5],
        [2, 7, 2, 7, 3],
        [1, 9, 0, 6, 4],
        [1, 3, 7, 2, 0]],

       [[7, 7, 7, 6, 7],
        [9, 8, 6, 9, 0],
        [9, 4, 7, 0, 5],
        [0, 9, 8, 7, 2]],

       [[9, 9, 6, 4, 9],
        [4, 0, 1, 8, 4],
        [7, 4, 4, 2, 9],
        [6, 1, 2, 0, 0]]])

In [84]:
x3[0,2,3]

6

In [85]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [8]:
#Another useful attribute is the dtype, the data type of the array and 
#itemsize,which lists the size (in bytes) of each array element,
#and nbytes, which lists the total size (in bytes) of the array:

In [9]:
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


#If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
#In a one-dimensional array, the $i^{th}$ value(counting from zero) can be accessed by specifying the
#desired index in square brackets, just as with Python lists:

In [10]:
x1

array([1, 7, 9, 0, 2, 0])

In [11]:
x1[1]

7

In [12]:
x1[0:2]

array([1, 7])

In [13]:
x1[ :4]

array([1, 7, 9, 0])

In [14]:
x1[2: ]

array([9, 0, 2, 0])

In [15]:
x1[-1]

0

In [16]:
x1[::2] #to index every other(2nd) element

array([1, 9, 2])

In [17]:
x1[::3]

array([1, 0])

In [6]:
x=np.arange(3,10,2)
x

array([3, 5, 7, 9])

In [19]:
x[::3] #index every 3rd element

array([0, 3, 6, 9])

In [20]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [21]:
x[2::3] # every 3rd element, starting at index2

array([2, 5, 8])

In [22]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [24]:
x[3::-2]  # reversed every other from index 3

array([3, 1])

In [25]:
x[5::-3]  # reversed every 3rd from index 5

array([5, 2])

In [26]:
#In a multi-dimensional array, items can be accessed using a comma

In [7]:
import numpy as np
x2 = np.random.randint(10, size=(3, 4))
x2

array([[0, 3, 9, 2],
       [4, 7, 1, 5],
       [6, 9, 8, 7]])

In [10]:
x2[1,1] #1 index row 1 index column element

7

In [29]:
x2[1,3] # second row 4th element

5

In [30]:
x2[2,-2] #2 index row last element

0

In [31]:
x2

array([[5, 5, 7, 5],
       [2, 5, 0, 5],
       [0, 2, 0, 8]])

In [32]:
x2[:2, :3]  # two rows, three columns

array([[5, 5, 7],
       [2, 5, 0]])

In [33]:
x2[:3, ::2]  # all rows, every other column

array([[5, 7],
       [2, 0],
       [0, 0]])

In [34]:
x2[::-1, ::-1] #Check this:subarray dimensions can even be reversed together:

array([[8, 0, 2, 0],
       [5, 0, 5, 2],
       [5, 7, 5, 5]])

In [35]:
#Accessing array's row and columns:
#One commonly needed routine is accessing of single rows or columns of an array.
#This can be done by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [36]:
print(x2[:, 0])  # first column of x2


[5 2 0]


In [37]:
print(x2[0, :])  # first row of x2

[5 5 7 5]


In [38]:
print(x2[0])  # equivalent to x2[0, :]In the case of row access,the empty slice can be omitted for a more compact syntax

[5 5 7 5]


In [39]:
print(x2[0, :])

[5 5 7 5]


In [40]:
print(x2[1])

[2 5 0 5]


In [41]:
print(x2[2])

[0 2 0 8]


In [42]:
#Values can also be modified using any of the above index notation

In [43]:
x2[0,3]=5
x2

array([[5, 5, 7, 5],
       [2, 5, 0, 5],
       [0, 2, 0, 8]])

In [44]:
x2[1,3]=6
x2

array([[5, 5, 7, 5],
       [2, 5, 0, 6],
       [0, 2, 0, 8]])

In [45]:
#Note:Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
#This means, for example, that if you attempt to insert a floating-point value
#to an integer array, the value will be silently truncated. 

In [46]:
x2[1,2]=3.42324324 #only 3 will be added rest will be truncated
x2

array([[5, 5, 7, 5],
       [2, 5, 3, 6],
       [0, 2, 0, 8]])

In [47]:
x1[0]=2.3432 #only integer will be added to array
x1

array([2, 7, 9, 0, 2, 0])

In [48]:
#One important–and extremely useful–thing to know about array slices is that they return views rather than copies of
#the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.

In [49]:
x2

array([[5, 5, 7, 5],
       [2, 5, 3, 6],
       [0, 2, 0, 8]])

In [50]:
x2_sub = x2[:2, :2] #Let's extract a 2 * 2 subarray from this
print(x2_sub)

[[5 5]
 [2 5]]


In [51]:
x2_sub[0, 0] = 44 # if we modify this subarray, we'll see that the original array is changed! 
print(x2_sub)

[[44  5]
 [ 2  5]]


In [52]:
x2 #observe

array([[44,  5,  7,  5],
       [ 2,  5,  3,  6],
       [ 0,  2,  0,  8]])

In [53]:
#Creating copies of arrays: it is sometimes useful to instead explicitly copy the data within an array or a subarray.
#This can be most easily done with the copy() method:

In [54]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[44  5]
 [ 2  5]]


In [55]:
x2_sub_copy[0, 0] = 42 #If we now modify this subarray, the original array is not touched:
print(x2_sub_copy)

[[42  5]
 [ 2  5]]


In [56]:
x2 #observe

array([[44,  5,  7,  5],
       [ 2,  5,  3,  6],
       [ 0,  2,  0,  8]])

In [57]:
#Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines np.concatenate, np.vstack,
#and np.hstack. np.concatenate takes a tuple or list of arrays as its first argument, as we can see here:

In [58]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [59]:
z = [99, 99, 99]  #You can also concatenate more than two arrays at once.
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [60]:
grid = np.array([[1, 2, 3],   #It can also be used for two-dimensional arrays:
                 [4, 5, 6]])

In [61]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [63]:
#For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack)
#and np.hstack (horizontal stack) functions:

In [64]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [65]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [66]:
#Splitting of arrays:The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, 
#and np.vsplit. For each of these, we can pass a list of indices giving the split points:

In [67]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [1,6])
print(x1, x2,x3)

[1] [ 2  3 99 99  3] [2 1]


In [68]:
#The related functions np.hsplit and np.vsplit are similar: let's take example
grid1 = np.arange(16).reshape((4, 4))
grid1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
upper, lower = np.vsplit(grid1, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [70]:
left, right = np.hsplit(grid1, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [71]:
#Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeated operations on
#values in NumPy arrays. Ufuncs are extremely flexible – before we saw an operation between a scalar and an array, but we can
#also operate between two arrays:

#Array arithmetic:NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators.
#The standard addition, subtraction, multiplication, and division can all be used:

In [72]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [73]:
#There is also a unary ufunc for negation, and a ** operator for exponentiation, and a % operator for modulus:

In [74]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [75]:
#In addition, these can be strung together however you wish, and the standard order of operations is respected:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [76]:
#Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy;
#for example, the + operator is a wrapper for the add function:
np.add(x, 2)

array([2, 3, 4, 5])

In [77]:
#The following table lists the arithmetic operators implemented in NumPy:
#Operator	Equivalent ufunc	Description
+	 np.add		 Addition (e.g., 1 + 1 = 2)
-	 np.subtract	 Subtraction (e.g., 3 - 2 = 1)
-	 np.negative	 Unary negation (e.g., -2)
*	 np.multiply	 Multiplication (e.g., 2 * 3 = 6)
/	 np.divide	 Division (e.g., 3 / 2 = 1.5)
//	 np.floor_divide	Floor division (e.g., 3 // 2 = 1)
**	 np.power	Exponentiation (e.g., 2 ** 3 = 8)
%	 np.mod	Modulus/remainder (e.g., 9 % 4 = 1)

SyntaxError: invalid syntax (<ipython-input-77-bbf51ad64e2d>, line 3)

In [ ]:
x = np.array([-2, -1, 0, 1, 2]) #The absolute value of a number is always positive.
abs(x)

In [ ]:
list(range(10))